### ISSUE TITLE
Wrong Sha sum?

### ISSUE THREAD

**Issue by Jojo144** [YunoHost-Apps/compteur_du_gase_ynh#3]
I tested an installation and it fails with "WARNING Corrupt source".

And indeed when I compute the sha256sum of the archive indicated in [conf/app.src](https://github.com/YunoHost-Apps/compteur_du_gase_ynh/blob/master/conf/app.src) I find f82f504bc9dfd446213c3030e000f1f6749a574d0ba35dd582d872c7fa7902e8 instead of what is given in this file.

Maybe caused by the renaming of the repo?

**Comment by yalh76** [comment]
maybe, I will upgrade

**Comment by Jojo144** [comment]
Merci ça a réglé le problème !
